fail_fast: true
repos:
-   repo: https://github.com/psf/black
    hooks:
    -   id: black
        name: Black Formatter
        language_version: python3.8
        stages:
            - commit
        language: system