fail_fast: false
repos:
-   repo: local
    hooks:
    -   id: black
        name: Black Formatter
        language_version: python3.8
        types:
            - python
        entry: black
        language: python