fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: check-byte-order-marker
    -   id: check-ast
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: Black Formatter
        language_version: python3.8
        types:
            - python
        entry: black
        language: python
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.6'  # or any later Vulture version
    hooks:
      - id: vulture
